"""
universe.py — Complete instrument universe for The Daily Edge.

Three source types:
  fred     — FRED API (rates, macro, credit spreads)
  yfinance — Yahoo Finance (ETFs, equities, FX, vol)
  derived  — computed from combinations of raw series
"""

# ── FRED SERIES: (series_id, human_label, asset_class) ───────────────────────
FRED_SERIES = [
    # US Rates
    ("DGS1MO",  "US 1M Treasury",            "rates"),
    ("DGS3MO",  "US 3M Treasury",            "rates"),
    ("DGS6MO",  "US 6M Treasury",            "rates"),
    ("DGS1",    "US 1Y Treasury",            "rates"),
    ("DGS2",    "US 2Y Treasury",            "rates"),
    ("DGS3",    "US 3Y Treasury",            "rates"),
    ("DGS5",    "US 5Y Treasury",            "rates"),
    ("DGS7",    "US 7Y Treasury",            "rates"),
    ("DGS10",   "US 10Y Treasury",           "rates"),
    ("DGS20",   "US 20Y Treasury",           "rates"),
    ("DGS30",   "US 30Y Treasury",           "rates"),
    ("DFEDTARU", "Fed Funds Target Upper",   "rates"),
    ("DFEDTARL", "Fed Funds Target Lower",   "rates"),
    ("SOFR",    "SOFR Overnight Rate",       "rates"),
    ("T10YIE",  "10Y Breakeven Inflation",   "rates"),
    ("T5YIE",   "5Y Breakeven Inflation",    "rates"),
    ("T10Y2Y",  "10Y-2Y Yield Spread",       "rates"),
    ("T10Y3M",  "10Y-3M Yield Spread",       "rates"),
    ("MORTGAGE30US", "30Y Mortgage Rate",    "rates"),
    ("DPRIME",  "Prime Rate",                "rates"),
    ("IORB",    "Interest on Reserves",      "rates"),
    # Credit spreads
    ("BAMLH0A0HYM2", "HY OAS Spread (ICE BofA)", "credit"),
    ("BAMLC0A0CM",   "IG OAS Spread (ICE BofA)", "credit"),
    ("TEDRATE",      "TED Spread",               "credit"),
    ("DCOILWTICO",   "WTI Crude Oil",             "commodity"),
    # US Macro
    ("CPIAUCSL",   "US CPI All Items",          "macro"),
    ("CPILFESL",   "US Core CPI",               "macro"),
    ("PCEPI",      "US PCE",                    "macro"),
    ("PCEPILFE",   "US Core PCE",               "macro"),
    ("UNRATE",     "US Unemployment Rate",      "macro"),
    ("PAYEMS",     "US Nonfarm Payrolls",        "macro"),
    ("ICSA",       "US Initial Jobless Claims", "macro"),
    ("CCSA",       "US Continuing Claims",      "macro"),
    ("INDPRO",     "US Industrial Production",  "macro"),
    ("CAPUTL",     "US Capacity Utilization",   "macro"),
    ("RETAILSMNSA","US Retail Sales (NSA)",     "macro"),
    ("RSXFS",      "US Retail Sales ex Autos",  "macro"),
    ("HOUST",      "US Housing Starts",         "macro"),
    ("PERMIT",     "US Building Permits",       "macro"),
    ("UMCSENT",    "US Consumer Sentiment",     "macro"),
    ("DSPIC96",    "US Real Disposable Income", "macro"),
    ("USREC",      "NBER Recession Indicator",  "macro"),
    ("BOGMBASE",   "US Monetary Base",          "macro"),
    ("M2SL",       "US M2 Money Supply",        "macro"),
    # International rates
    ("IRLTLT01DEM156N", "Germany 10Y Bund",     "rates"),
    ("IRLTLT01FRM156N", "France 10Y OAT",       "rates"),
    ("IRLTLT01ITM156N", "Italy 10Y BTP",        "rates"),
    ("IRLTLT01ESM156N", "Spain 10Y Bonos",      "rates"),
    ("IRLTLT01GBM156N", "UK 10Y Gilt",          "rates"),
    ("IRLTLT01JPM156N", "Japan 10Y JGB",        "rates"),
    ("IRLTLT01AUM156N", "Australia 10Y Bond",   "rates"),
    ("IRLTLT01CAM156N", "Canada 10Y Bond",      "rates"),
    ("IRLTLT01KRM156N", "South Korea 10Y Bond", "rates"),
    # International CPI
    ("DEUCPIALLMINMEI",   "Germany CPI",           "macro"),
    ("GBRCPIALLMINMEI",   "UK CPI",                "macro"),
    ("JPNCPIALLMINMEI",   "Japan CPI",             "macro"),
    ("CHNCPIALLMINMEI",   "China CPI",             "macro"),
    ("CP0000EZ19M086NEST","Eurozone HICP",         "macro"),
    ("CANCPIALLMINMEI",   "Canada CPI",            "macro"),
    ("AUSCPIALLMINMEI",   "Australia CPI",         "macro"),
    ("BRACPIALLMINMEI",   "Brazil CPI",            "macro"),
    ("INDCPIALLMINMEI",   "India CPI",             "macro"),
    ("KORCPIALLMINMEI",   "South Korea CPI",       "macro"),
    ("MEXCPIALLMINMEI",   "Mexico CPI",            "macro"),
    # International unemployment
    ("LRHUTTTTDEM156S",   "Germany Unemployment",  "macro"),
    ("LRHUTTTTGBM156S",   "UK Unemployment",       "macro"),
    ("LRHUTTTTJPM156S",   "Japan Unemployment",    "macro"),
    ("LRHUTTTTEZM156S",   "Eurozone Unemployment", "macro"),
    ("LRHUTTTTCAM156S",   "Canada Unemployment",   "macro"),
    ("LRHUTTTTAUM156S",   "Australia Unemployment","macro"),
    ("LRHUTTTTBRM156S",   "Brazil Unemployment",   "macro"),
    ("LRHUTTTTKOM156S",   "S. Korea Unemployment", "macro"),
    ("LRHUTTTTMXM156S",   "Mexico Unemployment",   "macro"),
    # International industrial production
    ("DEUPROINDMISMEI",   "Germany Industrial Production", "macro"),
    ("GBRPROINDMISMEI",   "UK Industrial Production",      "macro"),
    ("JPNPROINDMISMEI",   "Japan Industrial Production",   "macro"),
]

# ── YFINANCE TICKERS: (ticker, human_label, asset_class) ─────────────────────
YFINANCE_TICKERS = [
    # Bond duration ETFs
    ("SHY",  "iShares 1-3Y Treasury",      "rates"),
    ("IEI",  "iShares 3-7Y Treasury",      "rates"),
    ("IEF",  "iShares 7-10Y Treasury",     "rates"),
    ("TLH",  "iShares 10-20Y Treasury",    "rates"),
    ("TLT",  "iShares 20+Y Treasury",      "rates"),
    ("EDV",  "Vanguard Extended Duration", "rates"),
    ("ZROZ", "PIMCO Zero Coupon 25+Y",     "rates"),
    # TIPS
    ("TIP",  "iShares TIPS Bond",          "rates"),
    ("SCHP", "Schwab TIPS",                "rates"),
    ("VTIP", "Vanguard Short-Term TIPS",   "rates"),
    ("LTPZ", "PIMCO 15+Y TIPS",            "rates"),
    # Credit ETFs
    ("LQD",  "iShares IG Corporate",       "credit"),
    ("VCIT", "Vanguard Intermediate IG",   "credit"),
    ("VCLT", "Vanguard Long-Term IG",      "credit"),
    ("HYG",  "iShares High Yield Bond",    "credit"),
    ("JNK",  "SPDR High Yield Bond",       "credit"),
    ("ANGL", "VanEck Fallen Angels",       "credit"),
    ("FALN", "iShares Fallen Angels",      "credit"),
    ("BKLN", "Invesco Senior Loans",       "credit"),
    ("SRLN", "SPDR Senior Loans",          "credit"),
    # EM bonds
    ("EMB",  "iShares USD EM Sovereign",   "em"),
    ("VWOB", "Vanguard EM Government",     "em"),
    ("PCY",  "Invesco EM Sovereign USD",   "em"),
    ("EMHY", "iShares EM High Yield",      "em"),
    ("LEMB", "iShares EM Local Currency",  "em"),
    ("ELD",  "WisdomTree EM Local Debt",   "em"),
    # MBS
    ("MBB",  "iShares MBS",               "credit"),
    ("VMBS", "Vanguard MBS",              "credit"),
    ("CMBS", "iShares CMBS",              "credit"),
    # International government bonds
    ("BWX",  "SPDR International Treasury","rates"),
    ("IGOV", "iShares Intl Treasury",     "rates"),
    # Munis
    ("MUB",  "iShares National Muni",     "credit"),
    ("HYD",  "VanEck HY Muni",            "credit"),
    ("VTEB", "Vanguard Tax-Exempt",       "credit"),
    # US equity broad
    ("SPY",  "S&P 500",                   "equities"),
    ("QQQ",  "Nasdaq 100",                "equities"),
    ("IWM",  "Russell 2000",              "equities"),
    ("IWB",  "Russell 1000",              "equities"),
    ("VTI",  "Total US Market",           "equities"),
    ("DIA",  "Dow Jones Industrial",      "equities"),
    ("MDY",  "S&P MidCap 400",            "equities"),
    # GICS sectors
    ("XLC",  "Communication Services",   "equities"),
    ("XLY",  "Consumer Discretionary",   "equities"),
    ("XLP",  "Consumer Staples",         "equities"),
    ("XLE",  "Energy",                   "equities"),
    ("XLF",  "Financials",               "equities"),
    ("XLV",  "Health Care",              "equities"),
    ("XLI",  "Industrials",              "equities"),
    ("XLB",  "Materials",                "equities"),
    ("XLRE", "Real Estate",              "equities"),
    ("XLK",  "Technology",               "equities"),
    ("XLU",  "Utilities",                "equities"),
    # Factor ETFs
    ("MTUM", "iShares Momentum Factor",  "equities"),
    ("VLUE", "iShares Value Factor",     "equities"),
    ("QUAL", "iShares Quality Factor",   "equities"),
    ("USMV", "iShares Min Volatility",   "equities"),
    ("VIG",  "Vanguard Dividend Growth", "equities"),
    ("NOBL", "Dividend Aristocrats",     "equities"),
    ("SPHB", "Invesco High Beta",        "equities"),
    # Thematic
    ("ARKK", "ARK Innovation",           "equities"),
    ("SOXX", "iShares Semiconductors",   "equities"),
    ("HACK", "Cybersecurity ETF",        "equities"),
    ("ICLN", "iShares Clean Energy",     "equities"),
    ("JETS", "US Global Jets",           "equities"),
    ("ITB",  "iShares Homebuilders",     "equities"),
    ("KRE",  "SPDR Regional Banks",      "equities"),
    ("XBI",  "SPDR Biotech",             "equities"),
    ("GDX",  "VanEck Gold Miners",       "equities"),
    ("GDXJ", "VanEck Jr Gold Miners",    "equities"),
    # Country ETFs
    ("EWA",  "Australia ETF",            "em"),
    ("EWZ",  "Brazil ETF",               "em"),
    ("EWC",  "Canada ETF",               "equities"),
    ("MCHI", "iShares China ETF",        "em"),
    ("FXI",  "China Large Cap ETF",      "em"),
    ("ASHR", "China A-Shares ETF",       "em"),
    ("EWQ",  "France ETF",               "equities"),
    ("EWG",  "Germany ETF",              "equities"),
    ("INDA", "iShares India ETF",        "em"),
    ("EWI",  "Italy ETF",                "equities"),
    ("EWJ",  "Japan ETF",                "equities"),
    ("EWW",  "Mexico ETF",               "em"),
    ("EZA",  "South Africa ETF",         "em"),
    ("EWY",  "South Korea ETF",          "em"),
    ("EWT",  "Taiwan ETF",               "em"),
    ("TUR",  "Turkey ETF",               "em"),
    ("EWU",  "UK ETF",                   "equities"),
    ("EWH",  "Hong Kong ETF",            "em"),
    ("EIS",  "Israel ETF",               "equities"),
    ("EWD",  "Sweden ETF",               "equities"),
    ("EWL",  "Switzerland ETF",          "equities"),
    ("GREK", "Greece ETF",               "em"),
    ("KSA",  "Saudi Arabia ETF",         "em"),
    ("QAT",  "Qatar ETF",                "em"),
    ("ARGT", "Argentina ETF",            "em"),
    ("VNM",  "Vietnam ETF",              "em"),
    ("FM",   "Frontier Markets ETF",     "em"),
    # Regional blocs
    ("EEM",  "iShares EM Broad",         "em"),
    ("VWO",  "Vanguard EM Broad",        "em"),
    ("IEMG", "iShares Core EM",          "em"),
    ("EFA",  "iShares Developed ex-US",  "equities"),
    ("IEFA", "iShares Core Dev ex-US",   "equities"),
    ("VEA",  "Vanguard Dev ex-US",       "equities"),
    ("FEZ",  "SPDR Eurozone",            "equities"),
    ("EZU",  "iShares Eurozone",         "equities"),
    ("VGK",  "Vanguard Europe",          "equities"),
    ("VPL",  "Vanguard Pacific",         "equities"),
    ("AAXJ", "iShares Asia ex-Japan",    "em"),
    # Commodities
    ("GLD",  "SPDR Gold Shares",         "commodity"),
    ("IAU",  "iShares Gold",             "commodity"),
    ("SLV",  "iShares Silver",           "commodity"),
    ("PPLT", "Aberdeen Platinum",        "commodity"),
    ("USO",  "US Oil Fund (WTI)",        "commodity"),
    ("BNO",  "Brent Crude ETF",          "commodity"),
    ("UNG",  "US Natural Gas Fund",      "commodity"),
    ("UGA",  "US Gasoline Fund",         "commodity"),
    ("CORN", "Teucrium Corn",            "commodity"),
    ("WEAT", "Teucrium Wheat",           "commodity"),
    ("SOYB", "Teucrium Soybeans",        "commodity"),
    ("CANE", "Teucrium Sugar",           "commodity"),
    ("JO",   "iPath Coffee ETN",         "commodity"),
    ("NIB",  "iPath Cocoa ETN",          "commodity"),
    ("CPER", "US Copper Index ETF",      "commodity"),
    ("DBB",  "Invesco Base Metals",      "commodity"),
    ("PICK", "iShares Steel/Mining",     "commodity"),
    ("URA",  "Global X Uranium",         "commodity"),
    ("URNM", "Sprott Uranium Miners",    "commodity"),
    ("REMX", "VanEck Rare Earth",        "commodity"),
    ("PDBC", "Invesco Commodity",        "commodity"),
    ("DJP",  "iPath Bloomberg Commodity","commodity"),
    ("GSG",  "iShares GSCI Commodity",   "commodity"),
    # FX — G10
    ("EURUSD=X", "EUR/USD",              "fx"),
    ("GBPUSD=X", "GBP/USD",              "fx"),
    ("USDJPY=X", "USD/JPY",              "fx"),
    ("USDCHF=X", "USD/CHF",              "fx"),
    ("AUDUSD=X", "AUD/USD",              "fx"),
    ("NZDUSD=X", "NZD/USD",              "fx"),
    ("USDCAD=X", "USD/CAD",              "fx"),
    ("USDNOK=X", "USD/NOK",              "fx"),
    ("USDSEK=X", "USD/SEK",              "fx"),
    ("USDDKK=X", "USD/DKK",              "fx"),
    ("DX-Y.NYB", "US Dollar Index (DXY)","fx"),
    # FX — EM
    ("USDBRL=X", "USD/BRL",              "fx"),
    ("USDMXN=X", "USD/MXN",              "fx"),
    ("USDCLP=X", "USD/CLP",              "fx"),
    ("USDCOP=X", "USD/COP",              "fx"),
    ("USDZAR=X", "USD/ZAR",              "fx"),
    ("USDTRY=X", "USD/TRY",              "fx"),
    ("USDPLN=X", "USD/PLN",              "fx"),
    ("USDHUF=X", "USD/HUF",              "fx"),
    ("USDCZK=X", "USD/CZK",              "fx"),
    ("USDCNY=X", "USD/CNY",              "fx"),
    ("USDCNH=X", "USD/CNH (offshore)",   "fx"),
    ("USDINR=X", "USD/INR",              "fx"),
    ("USDIDR=X", "USD/IDR",              "fx"),
    ("USDPHP=X", "USD/PHP",              "fx"),
    ("USDMYR=X", "USD/MYR",              "fx"),
    ("USDTHB=X", "USD/THB",              "fx"),
    ("USDKRW=X", "USD/KRW",              "fx"),
    ("USDTWD=X", "USD/TWD",              "fx"),
    ("USDHKD=X", "USD/HKD",              "fx"),
    ("USDSGD=X", "USD/SGD",              "fx"),
    # Volatility
    ("^VIX",    "CBOE VIX (30D IV)",    "vol"),
    ("^VIX3M",  "CBOE 3M VIX",          "vol"),
    ("^SKEW",   "CBOE Skew Index",      "vol"),
    ("^VVIX",   "VIX of VIX",           "vol"),
    ("^GVZ",    "Gold Volatility",      "vol"),
    ("^OVX",    "Crude Oil Volatility", "vol"),
    ("VIXY",    "ProShares VIX ETP",    "vol"),
    # Crypto (risk context)
    ("BTC-USD", "Bitcoin",              "equities"),
    ("ETH-USD", "Ethereum",             "equities"),
]

# ── DERIVED SERIES: (id, human_label, asset_class) ───────────────────────────
DERIVED_SERIES = [
    ("2s10s",           "US 2s10s Yield Curve",       "rates"),
    ("2s30s",           "US 2s30s Yield Curve",       "rates"),
    ("5s30s",           "US 5s30s Yield Curve",       "rates"),
    ("3m10y",           "US 3M-10Y Yield Curve",      "rates"),
    ("curve_butterfly", "US Curve Butterfly",          "rates"),
    ("real_10y",        "US Real 10Y Yield",           "rates"),
    ("real_5y",         "US Real 5Y Yield",            "rates"),
    ("hyg_spy_ratio",   "HYG/SPY Ratio (normalized)", "credit"),
]


def get_all_series() -> list[dict]:
    """Return every instrument as a list of dicts with id/label/asset_class/source."""
    result = []
    for sid, label, ac in FRED_SERIES:
        result.append({"id": sid, "label": label, "asset_class": ac, "source": "fred"})
    for ticker, label, ac in YFINANCE_TICKERS:
        result.append({"id": ticker, "label": label, "asset_class": ac, "source": "yfinance"})
    for sid, label, ac in DERIVED_SERIES:
        result.append({"id": sid, "label": label, "asset_class": ac, "source": "derived"})
    return result


# Asset classes present in the universe
ALL_ASSET_CLASSES = ["rates", "fx", "em", "equities", "commodity", "credit", "macro", "vol"]

SECTION_LABELS = {
    "rates":     "Rates & Fixed Income",
    "fx":        "Foreign Exchange",
    "em":        "Emerging Markets",
    "equities":  "Equities",
    "commodity": "Commodities",
    "credit":    "Credit Markets",
    "macro":     "Macro & Economic Data",
    "vol":       "Volatility & Risk",
}
